# Generated by Django 4.1.7 on 2023-02-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('logo', models.ImageField(upload_to='logos/', verbose_name='Логотип сайта')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефонный номер')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('address_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Ссылка на адрес')),
                ('backround_image', models.ImageField(null=True, upload_to='backround_image/', verbose_name='Изображение на заднем плане в главной странице')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Ссылка на Facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Ссылка на instagram')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='Ссылка на WhatsApp')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Ссылка на Telegram')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
