# Generated by Django 4.1.7 on 2023-02-25 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='price_day',
            field=models.CharField(max_length=255, verbose_name='Цена за день'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('last_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone_number', models.CharField(max_length=100, verbose_name='Телефонный номер')),
                ('checked', models.BooleanField(default=False, verbose_name='Проверка')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('arrival_date', models.DateTimeField(verbose_name='Дата заезда')),
                ('departure_date', models.DateTimeField(verbose_name='Дата отьезда')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_reservation', to='rooms.rooms')),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Брони',
            },
        ),
    ]
