# Generated by Django 4.1.7 on 2023-02-25 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_rooms_price_day_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='first_name',
            new_name='name_1',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='last_name',
            new_name='name_2',
        ),
    ]
